package com.eaj.ufrn.mobilemilk.Enum;

public enum AnalisesSolicitadas {
    COMPOSICAO, CASEINA, PONTO_CRIOSCOPICO,
    CELULAS_SOMATICAS, NITROGENIO_UREICO, CONDUTIVIDADE_ELETRICA,
    RESIDUO_ANTIBIOTICO, ANALISES_FRAUDE, PH, SORO;
}
