package com.eaj.ufrn.mobilemilk.Enum;

public enum AnalisesSolicitadas {
    COMPOSICAO, CASEINA, PONTO_CRIOSCOPICO,
    CELULAS_SOMATICAS, NITROGENIO_UREICO, CONDUTIVIDADE_ELETRICA,
    RESIDUO_ANTIBIOTICO, PH, ACIDEZ_DORNIC, DENSIDADE_RELATIVA, CBT,
    FORMOL, AÇUCARES, ALCALINIZANTES, LACTOPEROXIDADE, CLORETOS, AMIDO;

    /*
    *  Obs -> as opções a baixo são referentes a análise de fraudes do leite
    *
    *  FORMOL, AÇUCARES, ALCALINIZANTES, LACTOPEROXIDADE, CLORETOS, AMIDO
    * */
}
